<?php
/**
 * The template for displaying the footer on the site.
 * It does not use tailwind, it's SCSS file can be found at ./assets/src/sass/components/footer.scss.
 * The "Footer Columns" generated by PHP can be configured in functions.php.
 *
 * Contains the footer of the site as well as WP's required code and the closing body and HTML tags.
 *
 * @link https://developer.wordpress.org/themes/basics/template-files/#template-partials
 *
 * @package WordPress
 * @subpackage Farmers_Only
 * @since 1.0.0
 */
?>

<!--Start Footer-->
<footer class="footer py-10">
    <div class="footer-bottom">
        <div class="bot-inner">

            <div class="social-links">
                <a href="<?php the_field( 'facebook', 'options' ); ?>" target="_blank" aria-label="Follow us on Facebook">
                    <i class="fa-brands fa-facebook"></i>
                </a>
            </div>

            <div class="social-links">
                <a href="<?php the_field( 'instagram', 'options' ); ?>" target="_blank" aria-label="Follow us on Instagram">
                    <i class="fa-brands fa-instagram"></i>
                </a>
            </div>

            <div class="social-links">
                <a href="mailto:<?php the_field( 'email', 'options' ); ?>" aria-label="Send us an email">
                    <i class="fa-light fa-envelope"></i>
                </a>
            </div>
            <!--Copyright Info-->
            <p class = "pt-5">© <?php echo date("Y"); ?> Land & Farm Acquisitions</p>
            <a href="/privacy-policy" class="hover:underline">Privacy Policy</a>
    </div>
</footer>
<!--End Footer-->


<!--Wordpress Requires This-->
<?php wp_footer(); ?>

</body>
</html>

